import tkinter as tk
from tkinter import ttk


class xiangxinxi(tk.Toplevel):
    def __init__(self, master=None, data=[], **kw):
        super(xiangxinxi, self).__init__(master, **kw)
        self.title('详细信息')
        self.frame19 = ttk.Frame(self)
        self.frame19.configure(height=500, width=300)
        self.frame20 = ttk.Frame(self.frame19)
        self.frame20.configure(height=200, width=200)
        self.label18 = ttk.Label(self.frame20)
        self.label18.configure(text='详细信息：')
        self.label18.pack(side="top")
        self.frame20.pack(side="top")
        self.frame21 = ttk.Frame(self.frame19)
        self.frame21.configure(height=200, width=200)
        self.frame23 = ttk.Frame(self.frame21)
        self.frame23.configure(height=200, width=200)
        self.frame25 = ttk.Frame(self.frame23)
        self.frame25.configure(height=200, width=200)
        self.label19 = ttk.Label(self.frame25)
        self.label19.configure(text='ID')
        self.label19.pack(side="left")
        self.entry1 = ttk.Entry(self.frame25)
        self.entry1.pack(side="right")
        self.frame25.pack(ipady=5, side="top")
        self.frame26 = ttk.Frame(self.frame23)
        self.frame26.configure(height=200, width=200)
        self.label20 = ttk.Label(self.frame26)
        self.label20.configure(text='用户名')
        self.label20.pack(side="left")
        self.entry2 = ttk.Entry(self.frame26)
        self.entry2.pack(side="top")
        self.frame26.pack(ipady=5, side="top")
        self.frame27 = ttk.Frame(self.frame23)
        self.frame27.configure(height=200, width=200)
        self.label21 = ttk.Label(self.frame27)
        self.label21.configure(text='类型')
        self.label21.pack(side="left")
        self.entry3 = ttk.Entry(self.frame27)
        self.entry3.pack(side="top")
        self.frame27.pack(ipady=5, side="top")
        self.frame28 = ttk.Frame(self.frame23)
        self.frame28.configure(height=200, width=200)
        self.label22 = ttk.Label(self.frame28)
        self.label22.configure(text='快递公司')
        self.label22.pack(side="left")
        self.entry4 = ttk.Entry(self.frame28)
        self.entry4.pack(side="top")
        self.frame28.pack(ipady=5, side="top")
        self.frame29 = ttk.Frame(self.frame23)
        self.frame29.configure(height=200, width=200)
        self.label23 = ttk.Label(self.frame29)
        self.label23.configure(text='快递单号')
        self.label23.pack(side="left")
        self.entry5 = ttk.Entry(self.frame29)
        self.entry5.pack(side="top")
        self.frame29.pack(ipady=5, side="top")
        self.frame30 = ttk.Frame(self.frame23)
        self.frame30.configure(height=200, width=200)
        self.label24 = ttk.Label(self.frame30)
        self.label24.configure(text='物品信息')
        self.label24.pack(side="left")
        self.entry6 = ttk.Entry(self.frame30)
        self.entry6.pack(side="top")
        self.frame30.pack(ipady=5, side="top")
        self.frame31 = ttk.Frame(self.frame23)
        self.frame31.configure(height=200, width=200)
        self.label25 = ttk.Label(self.frame31)
        self.label25.configure(text='状态')
        self.label25.pack(side="left")
        self.entry7 = ttk.Entry(self.frame31)
        self.entry7.pack(side="left")
        self.frame31.pack(ipady=5, side="top")
        self.frame32 = ttk.Frame(self.frame23)
        self.frame32.configure(height=200, width=200)
        self.label26 = ttk.Label(self.frame32)
        self.label26.configure(text='联系号码')
        self.label26.pack(side="left")
        self.entry8 = ttk.Entry(self.frame32)
        self.entry8.pack(side="top")
        self.frame32.pack(ipady=5, side="top")
        self.frame33 = ttk.Frame(self.frame23)
        self.frame33.configure(height=200, width=200)
        self.label27 = ttk.Label(self.frame33)
        self.label27.configure(text='备注')
        self.label27.pack(side="left")
        self.entry9 = ttk.Entry(self.frame33)
        self.entry9.pack(side="top")
        self.frame33.pack(ipady=5, side="top")
        self.frame34 = ttk.Frame(self.frame23)
        self.frame34.configure(height=200, width=200)
        self.label28 = ttk.Label(self.frame34)
        self.label28.configure(text='添加时间')
        self.label28.pack(side="left")
        self.entry10 = ttk.Entry(self.frame34)
        self.entry10.pack(ipadx=20, side="top")
        self.frame34.pack(ipady=5, side="top")
        self.frame35 = ttk.Frame(self.frame23)
        self.frame35.configure(height=200, width=200)
        self.label29 = ttk.Label(self.frame35)
        self.label29.configure(text='入库时间')
        self.label29.pack(side="left")
        self.entry11 = ttk.Entry(self.frame35)
        self.entry11.pack(ipadx=20, side="top")
        self.frame35.pack(ipady=5, side="top")
        self.frame36 = ttk.Frame(self.frame23)
        self.frame36.configure(height=200, width=200)
        self.label30 = ttk.Label(self.frame36)
        self.label30.configure(text='出库时间')
        self.label30.pack(side="left")
        self.entry12 = ttk.Entry(self.frame36)
        self.entry12.pack(ipadx=20, side="top")
        self.frame36.pack(ipady=5, side="top")
        self.frame37 = ttk.Frame(self.frame23)
        self.frame37.configure(height=200, width=200)
        self.label31 = ttk.Label(self.frame37)
        self.label31.configure(text='箱号')
        self.label31.pack(side="left")
        self.entry13 = ttk.Entry(self.frame37)
        self.entry13.pack(side="top")
        self.frame37.pack(ipady=5, side="top")
        self.frame23.pack(side="top")
        self.frame21.pack(side="top")
        self.frame22 = ttk.Frame(self.frame19)
        self.frame22.configure(height=200, width=200)
        self.frame24 = ttk.Frame(self.frame22)
        self.frame24.configure(height=200, width=200)
        self.frame24.pack(side="top")
        self.frame22.pack(side="top")
        self.frame19.pack(side="top")
        self.frame19.pack_propagate(0)
        self.configure(height=200, relief="raised", width=200)

        self.entry1.insert('0', data[0])
        self.entry2.insert('0', data[1])
        self.entry3.insert('0', data[2])
        self.entry4.insert('0', data[3])
        self.entry5.insert('0', data[4])
        self.entry6.insert('0', data[5])
        self.entry7.insert('0', data[6])
        self.entry8.insert('0', data[7])
        self.entry9.insert('0', data[8])
        self.entry10.insert('0', data[9])
        self.entry11.insert('0', data[10])
        self.entry12.insert('0', data[11])
        self.entry13.insert('0', str(data[12]))

        self.entry1.config(state='disabled')
        self.entry2.config(state='disabled')
        self.entry3.config(state='disabled')
        self.entry4.config(state='disabled')
        self.entry5.config(state='disabled')
        self.entry6.config(state='disabled')
        self.entry7.config(state='disabled')
        self.entry8.config(state='disabled')
        self.entry9.config(state='disabled')
        self.entry10.config(state='disabled')
        self.entry11.config(state='disabled')
        self.entry12.config(state='disabled')
        self.entry13.config(state='disabled')
